# general.py
from PyQt5 import QtWidgets

def create_general_tab(parent):
    general_widget = QtWidgets.QWidget()

    # Add UI elements for the General tab
    parent.autoplay_toggle = QtWidgets.QCheckBox("Auto-Play TTS", general_widget)
    parent.autoplay_toggle.stateChanged.connect(parent.toggle_autoplay)

    #launch at startup checkbox
    parent.startup_checkbox = QtWidgets.QCheckBox("Launch at Startup", general_widget)

    #minimize to system tray checkbox
    parent.tray_checkbox = QtWidgets.QCheckBox("Minimize to System Tray", general_widget)

    #Theme: Allows the user to choose between light and dark mode.
    parent.dark_mode_toggle = QtWidgets.QCheckBox("Dark Mode", general_widget)

    #langages dropdown
    parent.language_dropdown = QtWidgets.QComboBox(general_widget)
    parent.language_dropdown.addItem("Albanian")
    parent.language_dropdown.addItem("Arabic")
    parent.language_dropdown.addItem("Armenian")
    parent.language_dropdown.addItem("Awadhi")
    parent.language_dropdown.addItem("Azerbaijani")
    parent.language_dropdown.addItem("Bashkir")
    parent.language_dropdown.addItem("Basque")
    parent.language_dropdown.addItem("Belarusian")
    parent.language_dropdown.addItem("Bengali")
    parent.language_dropdown.addItem("Bhojpuri")
    parent.language_dropdown.addItem("Bosnian")
    parent.language_dropdown.addItem("Brazilian Portuguese")
    parent.language_dropdown.addItem("Bulgarian")
    parent.language_dropdown.addItem("Cantonese (Yue)")
    parent.language_dropdown.addItem("Catalan")
    parent.language_dropdown.addItem("Chhattisgarhi")
    parent.language_dropdown.addItem("Chinese")
    parent.language_dropdown.addItem("Croatian")
    parent.language_dropdown.addItem("Czech")
    parent.language_dropdown.addItem("Danish")
    parent.language_dropdown.addItem("Dogri")
    parent.language_dropdown.addItem("Dutch")
    parent.language_dropdown.addItem("English")
    parent.language_dropdown.addItem("Estonian")
    parent.language_dropdown.addItem("Faroese")
    parent.language_dropdown.addItem("Finnish")
    parent.language_dropdown.addItem("French")
    parent.language_dropdown.addItem("Galician")
    parent.language_dropdown.addItem("Georgian")
    parent.language_dropdown.addItem("German")
    parent.language_dropdown.addItem("Greek")
    parent.language_dropdown.addItem("Gujarati")
    parent.language_dropdown.addItem("Haryanvi")
    parent.language_dropdown.addItem("Hindi")
    parent.language_dropdown.addItem("Hungarian")
    parent.language_dropdown.addItem("Indonesian")
    parent.language_dropdown.addItem("Irish")
    parent.language_dropdown.addItem("Italian")
    parent.language_dropdown.addItem("Japanese")
    parent.language_dropdown.addItem("Javanese")
    parent.language_dropdown.addItem("Kannada")
    parent.language_dropdown.addItem("Kashmiri")
    parent.language_dropdown.addItem("Kazakh")
    parent.language_dropdown.addItem("Konkani")
    parent.language_dropdown.addItem("Korean")
    parent.language_dropdown.addItem("Kyrgyz")
    parent.language_dropdown.addItem("Latvian")
    parent.language_dropdown.addItem("Lithuanian")
    parent.language_dropdown.addItem("Macedonian")
    parent.language_dropdown.addItem("Maithili")
    parent.language_dropdown.addItem("Malay")
    parent.language_dropdown.addItem("Maltese")
    parent.language_dropdown.addItem("Mandarin Chinese")
    parent.language_dropdown.addItem("Marathi")
    parent.language_dropdown.addItem("Marwari")
    parent.language_dropdown.addItem("Min Nan")
    parent.language_dropdown.addItem("Moldovan")
    parent.language_dropdown.addItem("Mongolian")
    parent.language_dropdown.addItem("Montenegrin")
    parent.language_dropdown.addItem("Nepali")
    parent.language_dropdown.addItem("Norwegian")
    parent.language_dropdown.addItem("Oriya")
    parent.language_dropdown.addItem("Pashto")
    parent.language_dropdown.addItem("Persian (Farsi)")
    parent.language_dropdown.addItem("Polish")
    parent.language_dropdown.addItem("Portuguese")
    parent.language_dropdown.addItem("Punjabi")
    parent.language_dropdown.addItem("Rajasthani")
    parent.language_dropdown.addItem("Romanian")
    parent.language_dropdown.addItem("Russian")
    parent.language_dropdown.addItem("Sanskrit")
    parent.language_dropdown.addItem("Santali")
    parent.language_dropdown.addItem("Serbian")
    parent.language_dropdown.addItem("Sindhi")
    parent.language_dropdown.addItem("Sinhala")
    parent.language_dropdown.addItem("Slovak")
    parent.language_dropdown.addItem("Slovene")
    parent.language_dropdown.addItem("Slovenian")
    parent.language_dropdown.addItem("Swedish")
    parent.language_dropdown.addItem("Thai")
    parent.language_dropdown.addItem("Turkish")
    parent.language_dropdown.addItem("Ukrainian")
    parent.language_dropdown.addItem("Urdu")
    parent.language_dropdown.addItem("Uzbek")
    parent.language_dropdown.addItem("Vietnamese")
    parent.language_dropdown.addItem("Welsh")
    parent.language_dropdown.addItem("Wu")

    # Layout for General tab
    vbox = QtWidgets.QVBoxLayout()
    vbox.addWidget(parent.autoplay_toggle)
    vbox.addWidget(parent.startup_checkbox)
    vbox.addWidget(parent.tray_checkbox)

    general_widget.setLayout(vbox)
    return general_widget
